name: MytheriaHoppers
version: 1.0.0
main: me.mytheria.hoppers.MytheriaHoppers
api-version: '1.20'

depend:
  - Vault

softdepend:
  - CoinsEngine
  - SuperiorSkyblock2

commands:
  mytheriahoppers:
    description: Mytheria Hoppers administration command
    aliases:
      - mh
    usage: /mytheriahoppers <reload>

permissions:
  mytheriahoppers.use:
    description: Allows players to use Mytheria Hoppers
    default: true

  mytheriahoppers.filter:
    description: Allows unlocking and using the hopper item filter feature
    default: true

  mytheriahoppers.admin:
    description: Allows access to Mytheria Hoppers administration
    default: op

  mytheriahoppers.admin.reload:
    description: Allows reloading the Mytheria Hoppers configuration
    default: op

  mytheriahoppers.admin.bypass:
    description: Allows bypassing Mytheria Hopper restrictions
    default: op
