name: Build MytheriaHoppers

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Plugin
        run: mvn clean package

      - name: Upload Plugin Jar
        uses: actions/upload-artifact@v4
        with:
          name: MytheriaHoppers
          path: target/*.jar
